server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/socialmedia
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.oauth2: DEBUG